version: "3.8"
services:
  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    networks:
      - inner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"
    env_file: .env
  dynamo-admin:
    image: instructure/dynamo-local-admin
    container_name: "dynamoadmin_${PROJECT_NAME:-local_project}"
    networks:
      - inner
    ports:
      - "8000:8000"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    links:
      - localstack
  localstack:
    image: localstack/localstack:0.11.2
    container_name: "localstack_${PROJECT_NAME:-local_project}"
    networks:
      - inner
    env_file: .env
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_SERVICES=${LOCALSTACK_SERVICES- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=tcp://socat:2375
      - HOST_TMP_FOLDER=${PWD}
    volumes:
      - ${PWD}/.localstack/tmp/localstack:/tmp/localstack
    links:
      - socat
networks:
  inner:
    name: hexagonal_boilerplate
    driver: bridge
